### ISSUE TITLE
Can you add mongoose models to this project ? 

### ISSUE THREAD

**Issue by maisnamraju** [developit/express-es6-rest-api#2]
It would be nice to see this with mongoose for beginners like me.

**Comment by developit** [comment]
Yes, I think that would be a great addition. Do you think it would be best as a fork, or is it generally applicable?  I might start it as a fork..

**Comment by developit** [comment]
Perhaps using the module referenced from the readme as a starting point? https://gist.github.com/developit/ec2f438efc5feea4fd3a

**Comment by hzhu** [comment]
:+1:  for a fork. Mongoose should be a optional.

**Comment by developit** [comment]
@hzhu Will do, I agree that this is probably best kept as generic as possible.  Right now the only things on my radar in terms of updates to the boilerplate are adding eslint, updating dependencies, and transpiling to `lib/` instead of using the babel require hook (by default, with the current require hook behavior kept around as `npm run dev`).

**Comment by developit** [comment]
Closing for now as this issue is getting old - will create a fork for the mongoose integration.

**Comment by andre-dw** [comment]
You made this fork already? Or do you have an example to get me started. I'm new to nodejs and mongoose and want to create my first API.
