### ISSUE TITLE
Why database reference being posted as an argument in the example?

### ISSUE THREAD

**Issue by anton-aleksandrov** [developit/express-es6-rest-api#24]
Hey, 
Is this a common practice to initialize db on server start and then push it as am argument everywhere? I used to initialize it and expose it as a module to all other modules, so i can do something like this anywhere:
```javascript
import {update} from '../database'

export default (req, res) => {
  // yet another api method
}
```

Is the solution from this repo somehow better? It doesn't look more convenient. 

Thank you!

**Comment by developit** [comment]
Hi there! Exposing an instance of something stateful like a database connection by exporting it from a module is called a singleton. It works, but it makes things more difficult down the line - you can't instantiate anything that depends on the DB module because you cant pass things a different db. 

The technique shown here is just to use factories within each module, basically acting as a form of lightweight Dependency Injection. That way you can mix and match instances without running into cases that require mocking out the DB module. 

Hope that explanation helps!

**Comment by zouhir** [comment]
Well explained @developit! this has been inactive for a while and rather close it for now, hoping @anton-aleksandrov will re-open in case they've got any further question we are always happy to assist!
