### ISSUE TITLE
"babel: not found" while deploying to heroku

### ISSUE THREAD

**Issue by escobar5** [developit/express-es6-rest-api#36]
I get the error "Babel not found" while deploying to heroku.

I see heroku is calling the prestart script when deploying, should this prestart script work in production? do I have to do something else?

**Comment by hpdobrica** [comment]
I had the same problem, it's because heroku doesn't automatically install dev-dependencies for npm, you need to set config variable NPM_CONFIG_PRODUCTION in heroku to false and it will work :)

**Comment by adamchenwei** [comment]
@hpdobrica that seems not a long term solution... what is the core reason? I would like to see how it actually got resolved completely thanks a lot!

**Comment by developit** [comment]
This is just an oddity of Heroku - they run your build and deploy from Git (both development tools), but don't install development modules.  In general, I would recommend setting `NPM_CONFIG_PRODUCTION=false` on Heroku.

**Comment by chunkingz** [comment]
this worked for me, thanks guys

**Comment by nccharles** [comment]
in script use 

`"start:"babel-node index.js"` instead of using `"start:"babel index.js"`

**Comment by Direcious** [comment]
> in script use
> 
> `"start":"babel-node index.js"` instead of using `"start":"babel index.js"`

This should not be used for production.

**Comment by akash123456347** [comment]
Nothing working for me

**Comment by akash123456347** [comment]
can any one suggest how to use es6 in heroku with babel

**Comment by ricksterhd123** [comment]
> can any one suggest how to use es6 in heroku with babel

Hi today I've been trying to do this myself. I've figured it out. 
First, lets assume you setup babel correctly by using the command:
 `npm install --save-dev @babel/core @babel/cli` 

Inside package.json the result should be:
```
{
  "devDependencies": {
+   "@babel/cli": "^7.0.0",
+   "@babel/core": "^7.0.0"
  }
}
```

Now to the solution:
Other repo issues that mentioned this issue said you need to set the environment variable NPM_CONFIG_PRODUCTION=false, this can be done inside settings or via the console with command: `heroku config:set NPM_CONFIG_PRODUCTION=false`, and apparently the reason is because heroku does not install dev dependencies on production and in order for 'babel' to be defined development dependencies need to be installed. 

Hopefully this should fix yours and anyone else's issue.

**Comment by ricksterhd123** [comment]
Close this issue as it's nothing to do with this repository, this problem lies with Heroku.

**Comment by MicheleMaltese** [comment]
> I had the same problem, it's because heroku doesn't automatically install dev-dependencies for npm, you need to set config variable NPM_CONFIG_PRODUCTION in heroku to false and it will work :)

you are a lifesaver <3

**Comment by MaffooBristol** [comment]
You can just change your script to be `npx babel` rather than `babel`

**Comment by platr-nigeria** [comment]
> NPM_CONFIG_PRODUCTION

`ERROR: connect ECONNREFUSED 127.0.0.1:5432`

This is the error I get when I apply your fix. please help :(

**Comment by TheJarX** [comment]
Hey guys, if you still having this problem [this](https://github.com/react-boilerplate/react-boilerplate/issues/1818#issuecomment-350271686) worked for me
